import { MenuSection } from './types';

export const MENU_DATA: MenuSection[] = [
  {
    id: 'fatayer-savory',
    title: 'فطير حشو داخلي',
    emoji: '🥧',
    image: 'https://8upload.com/image/28fe73463a5771a8/52022918231425109695.jpg',
    subtitles: ['وسط', 'كبير'],
    items: [
      { name: 'تشيكن رانش', description: 'موزاريلا - زنجر - خضار - صوص رانش', prices: ['115', '150'], isPopular: true, isSpicy: true },
      { name: 'تشيكن باربيكيو', description: 'موزاريلا - زنجر - خضار - صوص باربيكيو', prices: ['110', '145'], isSpicy: true },
      { name: 'تشيكن زنجر', description: 'موزاريلا - زنجر - خضار', prices: ['110', '140'], isSpicy: true },
      { name: 'شاورما فراخ', description: 'شاورما فراخ - خضار - موزاريلا', prices: ['100', '135'] },
      { name: 'سجق', description: 'سجق - خضار - موزاريلا', prices: ['80', '115'] },
      { name: 'لحمة مفرومة', description: 'لحمة مفرومة - خضار - موزاريلا', prices: ['100', '135'] },
      { name: 'هوت دوج', description: 'هوت دوج - خضار - موزاريلا', prices: ['90', '130'] },
      { name: 'بسطرمة', description: 'موزاريلا - بسطرمة - خضار', prices: ['110', '140'] },
      { name: 'سلامي', description: 'خضار - موزاريلا - سلامي', prices: ['100', '135'] },
      { name: 'تونا', description: 'موزاريلا - تونا - خضار', prices: ['100', '140'] },
      { name: 'مشروم', description: 'خضار - موزاريلا - مشروم', prices: ['80', '115'] },
      { name: 'سوبر سوبريم', description: 'سلامى - هوت دوج - خضار - موزاريلا', prices: ['115', '145'], isPopular: true },
      { name: 'ميكس لحوم', description: 'لحمة - سجق - بسطرمة - خضار - موزاريلا', prices: ['125', '160'], isPopular: true },
      { name: 'ميكس فراخ', description: 'شاورما فراخ - زنجر - خضار - موزاريلا', prices: ['125', '160'], isSpicy: true },
      { name: 'ميكس جبن', description: 'جبنة رومى - جبنة شيدر - بريزيدون - خضار - موزاريلا', prices: ['115', '145'] },
    ]
  },
  {
    id: 'fatayer-sweet',
    title: 'ركن الفطير الحلو',
    emoji: '🍯',
    image: 'https://8upload.com/image/7e941e36d4afa120/WhatsApp-Image-2022-10-19-at-3.30.52-PM-500x375.jpeg',
    subtitles: ['صغير', 'وسط', 'كبير'],
    items: [
      { name: 'فطير سادة بالسكر', description: 'سمن - سكر', prices: ['20', '30', '45'] },
      { name: 'فطير بغاشة سكر ولبن', description: 'سمن - سكر - لبن', prices: ['-', '35', '40'] },
      { name: 'فطير بالكريمة', description: 'سمن - كريمة - سكر - لبن', prices: ['35', '45', '60'] },
      { name: 'فطير بالبسبوسة', description: 'بسبوسة - كريمة - سكر - لبن', prices: ['45', '55', '75'] },
      { name: 'فطير بالكنافة', description: 'كنافة - كريمة - سكر - لبن', prices: ['45', '55', '75'] },
      { name: 'فطير بسبوسة وكنافة', description: 'بسبوسة - كنافة - كريمة - سكر - لبن', prices: ['45', '55', '75'], isPopular: true },
      { name: 'فطيرة حجم عائلي', description: 'بسبوسة - كنافة - مكسرات - سكر - لبن', prices: ['100'], labels: ['حجم عائلي'] },
      { name: 'فطير موز ومكسرات', description: 'كريمة - موز - مكسرات - سكر - لبن', prices: ['60', '75', '100'] },
      { name: 'فطير بالقشطة', description: 'قشطة - كريمة - عسل نحل - مكسرات - سكر - لبن', prices: ['60', '75', '95'], isPopular: true },
      { name: 'فطير بالشوكولاتة', description: 'شوكلاته - كريمة', prices: ['55', '65', '85'] },
      { name: 'فطير شوكولاتة وموز', description: 'كريمه - شوكلاته - موز - مكسرات', prices: ['60', '75', '90'] },
      { name: 'فطير باللوتس', description: 'كريمة - لوتس', prices: ['55', '65', '85'] },
      { name: 'فطير بالبستاشيو', description: 'كريمة - بستاشيو', prices: ['65', '90', '120'], isPopular: true },
      { name: 'فطير مشلتت', description: 'بالسمن البلدي', prices: ['75', '85', '100'], isPopular: true },
      { name: 'رقاق طري', description: 'سعر الكيلو', prices: ['50'], labels: ['الكيلو'] },
      { name: 'رقاق ناشف', description: 'سعر الكيلو', prices: ['70'], labels: ['الكيلو'] },
    ]
  },
  {
    id: 'additions-sweet',
    title: 'إضافات الفطير الحلو',
    emoji: '🍯',
    image: 'https://8upload.com/image/7e941e36d4afa120/WhatsApp-Image-2022-10-19-at-3.30.52-PM-500x375.jpeg',
    items: [
      { name: 'شوكولاتة', prices: ['25'] },
      { name: 'لوتس', prices: ['25'] },
      { name: 'قشطة', prices: ['15'] },
      { name: 'مكسرات', prices: ['10'] },
      { name: 'لبن', prices: ['10'] },
    ]
  },
  {
    id: 'pizza-oriental',
    title: 'بيتزا شرقي',
    emoji: '🍕',
    image: 'https://8upload.com/image/730f0d20b6d4c90e/920228174853402770529.jpg',
    subtitles: ['وسط', 'كبير'],
    items: [
      { name: 'تشيكن رانش', description: 'موزاريلا - زنجر - خضار - صوص رانش', prices: ['115', '150'], isPopular: true, isSpicy: true },
      { name: 'تشيكن باربيكيو', description: 'موزاريلا - زنجر - خضار - صوص باربيكيو', prices: ['110', '145'], isSpicy: true },
      { name: 'تشيكن زنجر', description: 'موزاريلا - زنجر - خضار', prices: ['110', '140'], isSpicy: true },
      { name: 'شاورما فراخ', description: 'شاورما فراخ - خضار - موزاريلا', prices: ['100', '135'] },
      { name: 'سجق', description: 'سجق - خضار - موزاريلا', prices: ['80', '115'] },
      { name: 'لحمة مفرومة', description: 'لحمة مفرومة - خضار - موزاريلا', prices: ['100', '135'] },
      { name: 'هوت دوج', description: 'هوت دوج - خضار - موزاريلا', prices: ['90', '130'] },
      { name: 'بسطرمة', description: 'موزاريلا - بسطرمة - خضار', prices: ['110', '145'] },
      { name: 'سلامي', description: 'خضار - موزاريلا - سلامي', prices: ['100', '135'] },
      { name: 'تونا', description: 'موزاريلا - تونا - خضار', prices: ['100', '140'] },
      { name: 'مشروم', description: 'خضار - موزاريلا - مشروم', prices: ['80', '115'] },
      { name: 'سوبر سوبريم', description: 'سلامى - هوت دوج - خضار - موزاريلا', prices: ['115', '145'], isPopular: true },
      { name: 'ميكس لحوم', description: 'لحمة - سجق - بسطرمة - خضار - موزاريلا', prices: ['125', '160'], isPopular: true },
      { name: 'ميكس فراخ', description: 'شاورما فراخ - زنجر - خضار - موزاريلا', prices: ['125', '160'], isSpicy: true },
      { name: 'ميكس جبن', description: 'جبنة رومى - جبنة شيدر - بريزيدون - خضار - موزاريلا', prices: ['115', '145'] },
    ]
  },
  {
    id: 'pizza-italian',
    title: 'بيتزا إيطالي',
    emoji: '🍕',
    image: 'https://8upload.com/image/880546ff003f6b7a/___________________________________________.jpg',
    subtitles: ['صغير', 'وسط', 'كبير'],
    items: [
      { name: 'تشيكن رانش', description: 'موزاريلا - زنجر - صوص رانش - خضار', prices: ['85', '115', '150'], isPopular: true, isSpicy: true },
      { name: 'تشيكن باربيكيو', description: 'موزاريلا - زنجر - صوص باربيكيو - خضار', prices: ['80', '110', '145'], isSpicy: true },
      { name: 'تشيكن زنجر', description: 'موزاريلا - زنجر - خضار', prices: ['80', '110', '140'], isSpicy: true },
      { name: 'شاورما فراخ', description: 'موزاريلا - شاورما فراخ - خضار', prices: ['75', '100', '135'] },
      { name: 'سجق', description: 'موزاريلا - سجق - خضار', prices: ['60', '80', '115'] },
      { name: 'لحمة مفرومة', description: 'موزاريلا - لحمة مفرومة - خضار', prices: ['75', '100', '135'] },
      { name: 'هوت دوج', description: 'موزاريلا - هوت دوج - خضار', prices: ['70', '90', '130'] },
      { name: 'بسطرمة', description: 'موزاريلا - بسطرمة - خضار', prices: ['75', '110', '145'] },
      { name: 'تونا', description: 'موزاريلا - تونا - خضار', prices: ['-', '100', '140'] },
      { name: 'سلامي', description: 'موزاريلا - سلامي - خضار', prices: ['65', '100', '135'] },
      { name: 'مشروم', description: 'موزاريلا - مشروم - خضار', prices: ['60', '80', '115'] },
      { name: 'مارجريتا', description: 'موزاريلا - جبنة رومى', prices: ['55', '75', '95'] },
      { name: 'خضروات', description: 'موزاريلا - خضار - رومى', prices: ['55', '75', '95'] },
      { name: 'سوبر سوبريم', description: 'موزاريلا - سلامى - هوت دوج - خضار', prices: ['80', '115', '145'], isPopular: true },
      { name: 'ميكس لحوم', description: 'موزاريلا - لحمة - سجق - بسطرمة - خضار', prices: ['85', '125', '160'], isPopular: true },
      { name: 'ميكس فراخ', description: 'موزاريلا - شاورما فراخ - زنجر - خضار', prices: ['85', '125', '160'], isSpicy: true },
      { name: 'ميكس جبن', description: 'موزاريلا - جبنة رومى - جبنة شيدر - بريزيدون - خضار', prices: ['75', '115', '145'] },
    ]
  },
  {
    id: 'syrian',
    title: 'السندوتشات السوري',
    emoji: '🌯',
    image: 'https://8upload.com/image/a4d726b5142e8ffa/1031253834.jpg',
    subtitles: ['وسط', 'كبير'],
    items: [
      { name: 'بطاطس', prices: ['20', '30'] },
      { name: 'كريسبي', prices: ['35', '55'] },
      { name: 'شاورما فراخ', prices: ['40', '60'] },
      { name: 'زنجر', prices: ['45', '60'], isSpicy: true },
      { name: 'شاورما لحمة', prices: ['40', '75'] },
    ]
  },
  {
    id: 'crepe-savory',
    title: 'الكريب',
    emoji: '🌯',
    image: 'https://8upload.com/image/bfc256199bae5a80/WhatsApp_Image_2026-01-23_at_4.52.49_PM.jpeg',
    items: [
      { name: 'بطاطس', prices: ['40'] },
      { name: 'بانيه', prices: ['50', '60'], labels: ['عادي', 'دبل'] },
      { name: 'بطاطس وبانيه', prices: ['55'] },
      { name: 'هوت دوج', prices: ['60'] },
      { name: 'سجق', prices: ['60'] },
      { name: 'برجر', prices: ['70'] },
      { name: 'شيش', prices: ['75'] },
      { name: 'شاورما فراخ', prices: ['75'] },
      { name: 'فاهيتا فراخ', prices: ['75'] },
      { name: 'ميكس فراخ', prices: ['90'] },
      { name: 'ميكس لحوم', prices: ['90'] },
      { name: 'زنجر', prices: ['80'], isSpicy: true },
      { name: 'ميكس جبن', prices: ['75'] },
    ]
  },
  {
    id: 'crepe-sweet',
    title: 'الكريب الحلو',
    emoji: '🥞',
    image: 'https://8upload.com/image/8306f88516a43869/940.jpg',
    items: [
      { name: 'شوكولاتة', prices: ['50'] },
      { name: 'شوكولاتة موز ومكسرات', prices: ['60'] },
      { name: 'شوكولاتة أوريو ومكسرات', prices: ['60'] },
      { name: 'لوتس', prices: ['50'] },
    ]
  },
  {
    id: 'rolls',
    title: 'رول أطياب',
    emoji: '🌯',
    image: 'https://8upload.com/image/dbf48e125ce21870/maxresdefault.jpg',
    items: [
      { name: 'بطاطس', prices: ['65'] },
      { name: 'سجق', prices: ['80'] },
      { name: 'هوت دوج', prices: ['80'] },
      { name: 'لحمة مفرومة', prices: ['90'] },
      { name: 'شاورما فراخ', prices: ['90'] },
      { name: 'زنجر', prices: ['100'], isSpicy: true },
      { name: 'ميكس جبن', prices: ['110'] },
      { name: 'ميكس فراخ', prices: ['110'] },
      { name: 'ميكس لحوم', prices: ['115'] },
    ]
  },
  {
    id: 'additions-crepe',
    title: 'إضافات الكريب والسوري',
    emoji: '✨',
    image: 'https://8upload.com/image/7a16b4bade3e4811/WhatsApp_Image_2026-01-23_at_3.17.53_PM.jpeg',
    items: [
      { name: 'لحمة مفرومة', prices: ['20'] },
      { name: 'فراخ', prices: ['20'] },
      { name: 'مشروم', prices: ['15'] },
      { name: 'رومي', prices: ['15'] },
      { name: 'جبنة بريزيدون', prices: ['20'] },
      { name: 'بطاطس', prices: ['10'] },
      { name: 'رانش', prices: ['10'] },
      { name: 'باربيكيو', prices: ['10'] },
      { name: 'بانيه', prices: ['10'] },
      { name: 'شيدر', prices: ['15'] },
      { name: 'موزاريلا', prices: ['10'] },
      { name: 'كونو', prices: ['20'] },
      { name: 'لحوم (بسطرمة/سلامي)', prices: ['15', '25'], labels: ['عادي', 'دبل'] },
    ]
  },
  {
    id: 'additions-pizza',
    title: 'إضافات البيتزا والفطير',
    emoji: '✨',
    image: 'https://8upload.com/image/9e28caf58a10c434/maxresdefault__1_.jpg',
    items: [
      { name: 'إضافة جبن', prices: ['25', '40'], labels: ['عادي', 'دبل'] },
      { name: 'إضافة لحوم', prices: ['20', '40'], labels: ['عادي', 'دبل'] },
      { name: 'إضافة فراخ', prices: ['20', '40'], labels: ['عادي', 'دبل'] },
      { name: ' مشروم', prices: ['20', '35'], labels: ['عادي', 'دبل'] },
      { name: ' حشو اطراف جبن', prices: ['20', '35'], labels: ['عادي', 'دبل'] },
      { name: ' حشو اطراف لحوم', prices: ['35', '50'], labels: ['عادي', 'دبل'] },
      { name: ' حشو اطراف فراخ', prices: ['35', '50'], labels: ['عادي', 'دبل'] },
      { name: 'رانش', prices: ['10'] },
      { name: 'باربكيو', prices: ['10'] },
      { name: 'باكت بطاطس', prices: ['25'] },
    ]
  }
];
